USE [master]
GO

/****** Object:  Database [Tests]    Script Date: 9/7/2020 6:18:45 PM ******/
CREATE DATABASE [Tests]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tests', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Tests.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tests_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Tests_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tests].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tests] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tests] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tests] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tests] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tests] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tests] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tests] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tests] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tests] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tests] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tests] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tests] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tests] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tests] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tests] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tests] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tests] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tests] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tests] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tests] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tests] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tests] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tests] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tests] SET  MULTI_USER 
GO

ALTER DATABASE [Tests] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tests] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tests] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tests] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Tests] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tests] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tests] SET  READ_WRITE 
GO

