//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreationPlatform.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsResult
    {
        public int ResultID { get; set; }
        public int TestID { get; set; }
        public int CorrectAnswersTotal { get; set; }
        public int QuestionsTotal { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
